version: '3.8'

services:
  start-stream-asst:
    build: .
    container_name: start-stream-assistant
    ports:
      - "0.0.0.0::8080" 
    env_file:
      - .env
    volumes:
      - .:/app  
    working_dir: /app/src 
    command: python main.py
    restart: "no"
